// <auto-generated />
using System;
using FitnessApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FitnessApp.Models.Klijent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cilj")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KilazaPocetna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrenerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Visina")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrenerId");

                    b.ToTable("Klijenti", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.KlijentTrening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumDodjele")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlijentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreningId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlijentId");

                    b.HasIndex("TreningId");

                    b.ToTable("KlijentTreninzi", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.Misic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Misici", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.ProgressRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlijentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tezina")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("KlijentId");

                    b.ToTable("ProgressRecords", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.Sablon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrenerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrenerId");

                    b.ToTable("Sabloni", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.SablonStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojPonavljanja")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojSetova")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Redoslijed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SablonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrajanjeSekundi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VjezbaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SablonId");

                    b.HasIndex("VjezbaId");

                    b.ToTable("SablonStavke", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.Trener", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Certifikat")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Treneri", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.Trening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrajanjeMinuta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrenerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrenerId");

                    b.ToTable("Treninzi", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.Vjezba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeVremenska")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tezina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vrsta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vjezbe", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.VjezbaDodjela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojPonavljanja")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojSetova")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Redoslijed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrajanjeSekundi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreningId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VjezbaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TreningId");

                    b.HasIndex("VjezbaId");

                    b.ToTable("VjezbaDodjele", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Models.VjezbaMisic", b =>
                {
                    b.Property<int>("VjezbaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MisicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VjezbaId", "MisicId");

                    b.HasIndex("MisicId");

                    b.ToTable("VjezbaMisici");
                });

            modelBuilder.Entity("FitnessApp.Models.Klijent", b =>
                {
                    b.HasOne("FitnessApp.Models.Trener", "Trener")
                        .WithMany("Klijenti")
                        .HasForeignKey("TrenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trener");
                });

            modelBuilder.Entity("FitnessApp.Models.KlijentTrening", b =>
                {
                    b.HasOne("FitnessApp.Models.Klijent", "Klijent")
                        .WithMany("KlijentTreninzi")
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessApp.Models.Trening", "Trening")
                        .WithMany("KlijentTreninzi")
                        .HasForeignKey("TreningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Trening");
                });

            modelBuilder.Entity("FitnessApp.Models.ProgressRecord", b =>
                {
                    b.HasOne("FitnessApp.Models.Klijent", "Klijent")
                        .WithMany("ProgressZapisi")
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klijent");
                });

            modelBuilder.Entity("FitnessApp.Models.Sablon", b =>
                {
                    b.HasOne("FitnessApp.Models.Trener", "Trener")
                        .WithMany("Sabloni")
                        .HasForeignKey("TrenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trener");
                });

            modelBuilder.Entity("FitnessApp.Models.SablonStavka", b =>
                {
                    b.HasOne("FitnessApp.Models.Sablon", "Sablon")
                        .WithMany("SablonStavke")
                        .HasForeignKey("SablonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessApp.Models.Vjezba", "Vjezba")
                        .WithMany("SablonStavke")
                        .HasForeignKey("VjezbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sablon");

                    b.Navigation("Vjezba");
                });

            modelBuilder.Entity("FitnessApp.Models.Trening", b =>
                {
                    b.HasOne("FitnessApp.Models.Trener", "Trener")
                        .WithMany("Treninzi")
                        .HasForeignKey("TrenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trener");
                });

            modelBuilder.Entity("FitnessApp.Models.VjezbaDodjela", b =>
                {
                    b.HasOne("FitnessApp.Models.Trening", "Trening")
                        .WithMany("VjezbaDodjele")
                        .HasForeignKey("TreningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessApp.Models.Vjezba", "Vjezba")
                        .WithMany("VjezbaDodjele")
                        .HasForeignKey("VjezbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trening");

                    b.Navigation("Vjezba");
                });

            modelBuilder.Entity("FitnessApp.Models.VjezbaMisic", b =>
                {
                    b.HasOne("FitnessApp.Models.Misic", "Misic")
                        .WithMany("VjezbaMisici")
                        .HasForeignKey("MisicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Models.Vjezba", "Vjezba")
                        .WithMany("VjezbaMisici")
                        .HasForeignKey("VjezbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Misic");

                    b.Navigation("Vjezba");
                });

            modelBuilder.Entity("FitnessApp.Models.Klijent", b =>
                {
                    b.Navigation("KlijentTreninzi");

                    b.Navigation("ProgressZapisi");
                });

            modelBuilder.Entity("FitnessApp.Models.Misic", b =>
                {
                    b.Navigation("VjezbaMisici");
                });

            modelBuilder.Entity("FitnessApp.Models.Sablon", b =>
                {
                    b.Navigation("SablonStavke");
                });

            modelBuilder.Entity("FitnessApp.Models.Trener", b =>
                {
                    b.Navigation("Klijenti");

                    b.Navigation("Sabloni");

                    b.Navigation("Treninzi");
                });

            modelBuilder.Entity("FitnessApp.Models.Trening", b =>
                {
                    b.Navigation("KlijentTreninzi");

                    b.Navigation("VjezbaDodjele");
                });

            modelBuilder.Entity("FitnessApp.Models.Vjezba", b =>
                {
                    b.Navigation("SablonStavke");

                    b.Navigation("VjezbaDodjele");

                    b.Navigation("VjezbaMisici");
                });
#pragma warning restore 612, 618
        }
    }
}
